import LastRecordHouse from "@/components/icons/LastRecords/LastRecordHouse";
export const LastRecord = [
  {
    header: "Last Records",
    color: "",
    icon: <LastRecordHouse />,
    has: "-",
    num: " 1,000₮",
    p: "3 hours ago",
    h1: "Lending & Renting",
  },
  {
    header: "Last Records",
    color: "",
    icon: <LastRecordHouse />,
    has: "-",
    num: " 1,000₮",
    p: "3 hours ago",
    h1: "Lending & Renting",
  },
  {
    header: "Last Records",
    color: "",
    icon: <LastRecordHouse />,
    has: "-",
    num: " 1,000₮",
    p: "3 hours ago",
    h1: "Lending & Renting",
  },
  {
    header: "Last Records",
    color: "",
    icon: <LastRecordHouse />,
    has: "-",
    num: " 1,000₮",
    p: "3 hours ago",
    h1: "Lending & Renting",
  },
  {
    header: "Last Records",
    color: "",
    icon: <LastRecordHouse />,
    has: "-",
    num: " 1,000₮",
    p: "3 hours ago",
    h1: "Lending & Renting",
  },
  {
    header: "Last Records",
    color: "",
    icon: <LastRecordHouse />,
    has: "-",
    num: " 1,000₮",
    p: "3 hours ago",
    h1: "Lending & Renting",
  },
];
