import { FaHouse } from "react-icons/fa6";
export const lastrecord = [
  {
    color: "",
    icon: <FaHouse className=" fill-white" />,
    has: "-",
    num: " 1,000₮",
    p: "3 hours ago",
    h1: "Lending & Renting",
  },
  {
    color: "",
    icon: <FaHouse className="fill-white" />,
    has: "-",
    num: " 1,000₮",
    p: "3 hours ago",
    h1: "Lending & Renting",
  },
  {
    color: "",
    icon: <FaHouse className="fill-white" />,
    has: "-",
    num: " 1,000₮",
    p: "3 hours ago",
    h1: "Lending & Renting",
  },
  {
    color: "",
    icon: <FaHouse className="fill-white" />,
    has: "-",
    num: " 1,000₮",
    p: "3 hours ago",
    h1: "Lending & Renting",
  },
  {
    color: "",
    icon: <FaHouse className="fill-white" />,
    has: "-",
    num: " 1,000₮",
    p: "3 hours ago",
    h1: "Lending & Renting",
  },
  {
    color: "",
    icon: <FaHouse className="fill-white" />,
    has: "-",
    num: " 1,000₮",
    p: "3 hours ago",
    h1: "Lending & Renting",
  },
];
